In [2]:
import pandas as pd

In [3]:
taxonomy_excel = pd.read_excel("/home/rszczygielski/bioinf/magisterka/geneBank/results/main_mitochondrion_no_location.xlsx")
taxonomy_excel1 = pd.read_excel("/home/rszczygielski/bioinf/magisterka/geneBank/results/main_mitochondrion_based_on_location.xlsx")

In [4]:
joined_data = taxonomy_excel.merge(taxonomy_excel1,
                            indicator=True,
                            how="outer")

discrepancies_df = joined_data.loc[lambda x: x["_merge"] != "both"]
discrepancies_df['APPROACH'] = discrepancies_df['_merge'].apply(lambda x: 'NoLocation' if x == 'left_only' else "WithLocation")
discrepancies_df = discrepancies_df.drop('_merge', axis=1)
discrepancies_df = discrepancies_df.sort_values(["ACCESSION", "APPROACH"])
discrepancies_df = discrepancies_df.set_index("ACCESSION")
display(discrepancies_df.columns)
display(discrepancies_df)

/tmp/ipykernel_12282/3614086555.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  discrepancies_df['APPROACH'] = discrepancies_df['_merge'].apply(lambda x: 'NoLocation' if x == 'left_only' else "WithLocation")

Index(['ORGANISM', 'TAXONOMY', 'PREVIOUS_GENE_NAME', 'PREVIOUS_GENE_LOCATION',
       'PREVIOUS_GENE_PRODUCT_NAME', 'CONTROL_REGION_NAME',
       'CONTROL_REGION_LOCATION', 'NEXT_GENE_NAME', 'NEXT_GENE_LOCATION',
       'NEXT_GENE_PRODUCT_NAME', 'SURROUNDING_PAIRS', 'APPROACH'],
      dtype='object')

,ORGANISM,TAXONOMY,PREVIOUS_GENE_NAME,PREVIOUS_GENE_LOCATION,PREVIOUS_GENE_PRODUCT_NAME,CONTROL_REGION_NAME,CONTROL_REGION_LOCATION,NEXT_GENE_NAME,NEXT_GENE_LOCATION,NEXT_GENE_PRODUCT_NAME,SURROUNDING_PAIRS,APPROACH
ACCESSION,,,,,,,,,,,,
NC_001453.1,Strongylocentrotus purpuratus,"['Eukaryota', 'Metazoa', 'Echinodermata', 'Ele...",tRNA,1014:1084,tRNA-Thr,misc_feature,1085:1205,regulatory,1187:1196,NaN,tRNA-Thr_None,NoLocation
NC_001453.1,Strongylocentrotus purpuratus,"['Eukaryota', 'Metazoa', 'Echinodermata', 'Ele...",tRNA,1014:1084,tRNA-Thr,misc_feature,1085:1205,tRNA,1206:1275,tRNA-Pro,tRNA-Thr_tRNA-Pro,WithLocation
NC_001573.1,Xenopus laevis,"['Eukaryota', 'Metazoa', 'Chordata', 'Craniata...",tRNA,17485:17553,tRNA-Pro,D-loop,1:2134,rep_origin,1562:1601,NaN,tRNA-Pro_None,NoLocation
NC_001573.1,Xenopus laevis,"['Eukaryota', 'Metazoa', 'Chordata', 'Craniata...",tRNA,17485:17553,tRNA-Pro,D-loop,1:2134,tRNA,2136:2204,tRNA-Phe,tRNA-Pro_tRNA-Phe,WithLocation
NC_002609.1,Triatoma dimidiata,"['Eukaryota', 'Metazoa', 'Ecdysozoa', 'Arthrop...",rRNA,14074:14854,s-rRNA,misc_feature,14855:17019,stem_loop,16974:17015,NaN,s-rRNA_None,NoLocation
...,...,...,...,...,...,...,...,...,...,...,...,...
NC_066913.1,Cottus rhotheus,"['Eukaryota', 'Metazoa', 'Chordata', 'Craniata...",tRNA,7100:7172,tRNA-Asp,D-loop,7174:7199,tRNA,7890:7963,tRNA-Lys,tRNA-Asp_tRNA-Lys,WithLocation
NC_066972.1,Thyrsites atun,"['Eukaryota', 'Metazoa', 'Chordata', 'Craniata...",tRNA,15691:15763,tRNA-Pro,D-loop,15763:16494,tRNA,1:65,tRNA-Phe,tRNA-Pro_tRNA-Phe,NoLocation
NC_066972.1,Thyrsites atun,"['Eukaryota', 'Metazoa', 'Chordata', 'Craniata...",tRNA,15620:15694,tRNA-Thr,D-loop,15763:16494,tRNA,1:65,tRNA-Phe,tRNA-Thr_tRNA-Phe,WithLocation
NC_067054.1,Amphionides reynaudii,"['Eukaryota', 'Metazoa', 'Ecdysozoa', 'Arthrop...",CDS,13253:14191,NADH dehydrogenase subunit 1,D-loop,14222:14257,tRNA,14229:14295,tRNA-Leu,NADH dehydrogenase subunit 1_tRNA-Leu,NoLocation
NC_067054.1,Amphionides reynaudii,"['Eukaryota', 'Metazoa', 'Ecdysozoa', 'Arthrop...",CDS,13253:14191,NADH dehydrogenase subunit 1,D-loop,14222:14257,rRNA,14271:15595,l-rRNA,NADH dehydrogenase subunit 1_16S ribosomal RNA,WithLocation

In [7]:
only_accession = discrepancies_df.drop(['TAXONOMY', 'PREVIOUS_GENE_NAME', 'PREVIOUS_GENE_LOCATION',
       'PREVIOUS_GENE_PRODUCT_NAME', 'CONTROL_REGION_NAME',
       'CONTROL_REGION_LOCATION', 'NEXT_GENE_NAME', 'NEXT_GENE_LOCATION',
       'NEXT_GENE_PRODUCT_NAME'], axis=1)
display(only_accession)

,ORGANISM,SURROUNDING_PAIRS,APPROACH
ACCESSION,,,
NC_001453.1,Strongylocentrotus purpuratus,tRNA-Thr_None,NoLocation
NC_001453.1,Strongylocentrotus purpuratus,tRNA-Thr_tRNA-Pro,WithLocation
NC_001573.1,Xenopus laevis,tRNA-Pro_None,NoLocation
NC_001573.1,Xenopus laevis,tRNA-Pro_tRNA-Phe,WithLocation
NC_002609.1,Triatoma dimidiata,s-rRNA_None,NoLocation
...,...,...,...
NC_066913.1,Cottus rhotheus,tRNA-Asp_tRNA-Lys,WithLocation
NC_066972.1,Thyrsites atun,tRNA-Pro_tRNA-Phe,NoLocation
NC_066972.1,Thyrsites atun,tRNA-Thr_tRNA-Phe,WithLocation
NC_067054.1,Amphionides reynaudii,NADH dehydrogenase subunit 1_tRNA-Leu,NoLocation
NC_067054.1,Amphionides reynaudii,NADH dehydrogenase subunit 1_16S ribosomal RNA,WithLocation

In [8]:
discrepancies_df.to_excel("/home/rszczygielski/bioinf/magisterka/geneBank/data_analysis/comparison.xlsx")
only_accession.to_excel("/home/rszczygielski/bioinf/magisterka/geneBank/data_analysis/comparison_short.xlsx")

In [13]:
mammals_tasxonomy_string = "RodentiaChiropteraSoricomorphaPrimatesCarnivoraArtiodactylaDiprotodontiaLagomorphaDidelphimorphiaCetaceaDasyuromorphiaAfrosoricidaErinaceomorphaCingulataPeramelemorphiaScandentiaPerissodactylaMacroscelideaPilosaMonotremataSireniaProboscidea"

def get_taxonomy_list(main_sting):
    new_str = ""
    for elem in main_sting:
        if elem.isupper():
            new_str += f" {elem}"
        else:
            new_str += elem
    return new_str.split()

mammals_taxonomy_list = get_taxonomy_list(mammals_tasxonomy_string)

mammals_df = pd.DataFrame({"Mammals": mammals_taxonomy_list})
display(mammals_df)

            Mammals
0          Rodentia
1        Chiroptera
2      Soricomorpha
3          Primates
4         Carnivora
5      Artiodactyla
6     Diprotodontia
7        Lagomorpha
8   Didelphimorphia
9           Cetacea
10   Dasyuromorphia
11     Afrosoricida
12   Erinaceomorpha
13        Cingulata
14  Peramelemorphia
15       Scandentia
16   Perissodactyla
17    Macroscelidea
18           Pilosa
19      Monotremata
20          Sirenia
21      Proboscidea